version: '3'

services:
  client:
    image: node:12
    volumes:
      - ./client:/app
    working_dir: /app
    command: bash -c "[ -f 'node_modules' ] || npm i && npm run dev"
    ports:
      - '3000:3000'
    depends_on:
      - server
  server:
    image: strapi/strapi
    environment:
      NODE_VERSION: 12
      DATABASE_CLIENT: mongo
      DATABASE_HOST: db
      DATABASE_NAME: notas
      DATABASE_PORT: 27017
      DATABASE_USERNAME: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./server:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - db

  db:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: notas
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'
