version: '2'

services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./proxy/certs:/etc/nginx/certs:ro"

  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./proxy/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - DEBUG=true

  # client:
    #  restart: always
    # build:  ./client
    # environment:
    #   NODE_ENV: production
        # VIRTUAL_HOST: ${HOST_CLIENT}
        # VIRTUAL_NETWORK: nginx-proxy
        # LETSENCRYPT_HOST: ${HOST_CLIENT}
        # LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    # depends_on:
    #   - server

  server:
    restart: always
    build:  ./server
    environment:
      # NODE_ENV: production
      DATABASE_HOST: db
      DATABASE_NAME: notas
      DATABASE_PORT: 27017
      DATABASE_USERNAME: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      
      VIRTUAL_HOST: ${HOST_SERVER}
      VIRTUAL_NETWORK: nginx-proxy
      LETSENCRYPT_HOST: ${HOST_SERVER}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    depends_on:
      - db

  db:
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/db:/data/db
      - ./data/backup:/data/backup
